name: Create Release

on:
  push:
    tags:
      - "v*"

# Add permissions block
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        run: |
          chmod +x create_release.sh
          ./create_release.sh

      - name: Debug Directory Contents
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nBuild directory contents:"
          ls -la build/

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: Speed.app.zip
          draft: false
          prerelease: false

      - name: Update Appcast
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add appcast.xml
          git commit -m "Update appcast.xml for ${{ github.ref }}" || echo "No changes to commit"
          git push
