name: Create Release

on:
  push:
    tags:
      - "v*"

# Add permissions block
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Speed.app.zip
            signature.txt
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Update Appcast
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add appcast.xml
          git commit -m "Update appcast.xml for ${{ github.ref }}" || echo "No changes to commit"
          git push
